13:4: not a valid test operator: (
13:4: not a valid test operator: 470.129.06
Traceback (most recent call last):
  File "/home/gharatappeh/nips/src/prune.py", line 575, in <module>
    main()
  File "/home/gharatappeh/nips/src/prune.py", line 560, in main
    args = utils.get_yaml_args(args)
  File "/home/gharatappeh/nips/src/utils.py", line 273, in get_yaml_args
    network_conf = config_obj["network"]
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'network'
