13:4: not a valid test operator: (
13:4: not a valid test operator: 525.85.12
Traceback (most recent call last):
  File "prune.py", line 593, in <module>
    main()
  File "prune.py", line 578, in main
    args = utils.get_yaml_args(args)
  File "/home/gharatappeh/nips/src/utils.py", line 295, in get_yaml_args
    run_dir = get_run_dir(args)
  File "/home/gharatappeh/nips/src/utils.py", line 185, in get_run_dir
    checkdir(run_dir)
  File "/home/gharatappeh/nips/src/utils.py", line 27, in checkdir
    os.makedirs(directory)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/gharatappeh/nips/output/performance/resnet18/CIFAR10/cntr/14/02-48/'
