13:4: not a valid test operator: (
13:4: not a valid test operator: 470.129.06
Traceback (most recent call last):
  File "prune.py", line 567, in <module>
    main()
  File "prune.py", line 551, in main
    logger = utils.setup_logger_dir(args)
  File "/home/gharatappeh/nips/src/utils.py", line 158, in setup_logger_dir
    run_dir = get_run_dir(args)
  File "/home/gharatappeh/nips/src/utils.py", line 185, in get_run_dir
    checkdir(run_dir)
  File "/home/gharatappeh/nips/src/utils.py", line 27, in checkdir
    os.makedirs(directory)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/gharatappeh/nips/output/performance/resnet18/MNIST/no_cntr/12-47/'
